---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{}
configure: using libpng dynamic linkage
checking for X... libraries , headers 
checking GL/gl.h usability... yes
checking GL/gl.h presence... yes
checking for GL/gl.h... yes
checking GL/glu.h usability... no
checking GL/glu.h presence... no
checking for GL/glu.h... no
configure: error: missing required header GL/glu.h
ERROR: configuration failed for package ‘rgl’
* removing ‘/home/staff/rata/unix/Library/R/3.4/library/rgl’
Warning in install.packages :
  installation of package ‘rgl’ had non-zero exit status
ERROR: dependency ‘readbitmap’ is not available for package ‘imager’
* removing ‘/home/staff/rata/unix/Library/R/3.4/library/imager’
Warning in install.packages :
  installation of package ‘imager’ had non-zero exit status
ERROR: dependencies ‘rgl’, ‘imager’ are not available for package ‘rayshader’
* removing ‘/home/staff/rata/unix/Library/R/3.4/library/rayshader’
Warning in install.packages :
  installation of package ‘rayshader’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpi63zua/downloaded_packages’

```

Anscheinend scheiterte die Installation an zwei Packages, `rgl`und `imager`. Versuchen wir diese zu installieren:

```{}
install.packages("rgl")
```


```{}
checking GL/glu.h usability... no
checking GL/glu.h presence... no
checking for GL/glu.h... no
configure: error: missing required header GL/glu.h
ERROR: configuration failed for package ‘rgl’
* removing ‘/home/staff/rata/unix/Library/R/3.4/library/rgl’
Warning in install.packages :
  installation of package ‘rgl’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpjg0irM/downloaded_packages’
```

So was klingt nach einem ernsteren Problem. Jetzt hilft nur noch den relevanten Teil in diesem Fall `configure: error: missing required header GL/glu.h` zu googlen. 

Versuchen wir mal, `imager` zu installieren:

```{}
install.packages("imager")
```


```{}
* installing *source* package ‘readbitmap’ ...
** package ‘readbitmap’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Error: package ‘png’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
Execution halted
ERROR: lazy loading failed for package ‘readbitmap’
* removing ‘/home/staff/rata/unix/Library/R/3.4/library/readbitmap’
Warning in install.packages :
  installation of package ‘readbitmap’ had non-zero exit status
ERROR: dependency ‘readbitmap’ is not available for package ‘imager’
* removing ‘/home/staff/rata/unix/Library/R/3.4/library/imager’
Warning in install.packages :
  installation of package ‘imager’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpjg0irM/downloaded_packages’
```


Die Zeile `Error: package ‘png’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version` weist darauf hin, dass `png` nochmals installiert werden muss.

```{}
install.packages("png")
```


```{}
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (png)

The downloaded source packages are in
	‘/tmp/Rtmpjg0irM/downloaded_packages
```

Das sieht gut aus (keine `non-zero exit status`-Meldung. Zur Sicherheit an dieser Stelle einmal die Sesion neu starten (Session -> Restart R). Entweder wir probiere es mich nochmal mit `imager` oder mit der anderen Fehlermeldung (`readbitmap`). 

```{}
install.packages("readbitmap")
```

```{}
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (readbitmap)

The downloaded source packages are in
	‘/tmp/RtmpgIb0XU/downloaded_packages’
```

Das sieht gut aus. Jetzt nochmals mit `imager`

```{}
install.packages("imager")
```

```{}
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (imager)

The downloaded source packages are in
```

Hat geklappt! N
