---
title: "Übungen Statistik"
author: "Gian-Andrea Egeler"
date: "13 9 2018"
output: html_document
---

### Erläuterungen zum Datensatz

Folgende Variablen sind im Datensatz beinhaltet:


|   Name der Variable	|   Beschreibung der Variable	|   
|---	|---	|
|   "transaction_id" |  Durch das Kassensystem generierte Identifikationsnummer	| 
|   "date"	|   Datum	|
|  "week" | Kalenderwoche |
|  "year" | Kalenderjahr  |
|  "meal_name" | Beschreibung der angebotenen Mahlzeit  |
|  "article_description" | Beschreibung der Men?-Linie (Favorite, Hot and Cold Buffet, Kitchen, Locals<sup>1</sup>, World)  |
|  "label_content" | Beschreibung des Menü-Inhalts (Fleisch<sup>2</sup>, Hot and Cold, Vegan<sup>3</sup>, Vegetarisch<sup>4</sup>)  |
|  "condit" | Beschreibung der Experimentalwochen (Basis- und Interventionswochen)  |
|  "card_num" | anonymisierte Kartennummer  |
|  "gender" | Geschlecht (F,M)  |
|  "member" | Hochschulzugehörigkeit (Studierdne, Mitarbeitende, "Lernende", "Spezialkarten")  |
|  "age" |  Alter in Jahren |
|  "price_acticle" |  Preis des gekauften Artikels |
|  "total_amount_pay" | Total bezahlter Betrag  |
|  "pay_description" | Bezahlungsart (Cash oder Badge (Debit))  |
|  "shop_description" | Ort der Mensa (Grüental oder Vista)  |
|  "tot_ubp" | Umweltbelastungspunkte pro Menü  |
|  "buffet_anmial" | Anzahl fleischhaltiger Produkte auf dem Hot and Cold Buffet |

--------

**Bemerkungen:**

1. Locals (Local Favorite, Local Kitchen, Local World) sind nebst den drei "normalen Menü-Linien" zusätzlich angebotene Menüs
2. hier werden Menüs mit Fisch, Geflügel als Fleisch zusammengefasst
3. Vegan sind ausschliesslich pflanzliche Menüs. Im Exeriment wurde zwischen pflanzlich substituierten und authentisch eigenständige Menüs unterschieden
4. Vegetarisch sind ovo-lakto-vegetarische Menüs


<br><br>

### Aufgabe 4: Regression


Aufgabenstellung hier


### Musterlösung Aufgabe 4

```{r, message=FALSE, echo=FALSE, results='hide', warning=FALSE}

library(readr)
library(dplyr)
library(car)
library(gmodels)
library(ggfortify)

nova <- read_delim("/home/egel/Unterrichtsunterlagen_HS18/13_Statistik1/data/novanimal.csv", delim = ";")

```


