```{r}
brett <- st_multipoint(matrix(c(0,0,1,0,1,1,0,1),ncol = 2,byrow = TRUE)) %>%
  st_make_grid(n = c(10,10)) %>%
  st_as_sf() 
  
schachbrett <- brett %>%
  mutate(
    wert = rep(c(rep(c(1,0),5),rep(c(0,1),5)),5)
    )




ggplot(schachbrett) + geom_sf(aes(fill = factor(wert))) + 
  scale_fill_manual(values = c("black","white")) + 
  theme_void() +
  theme(legend.position = "none")
```

```{r, echo = TRUE}
mornans_i(sf_object = schachbrett,col = "wert")

```


```{r}
brett1 <- brett %>% 
  mutate(wert = c(rep(1,50),rep(2,50)))

ggplot(brett1) + geom_sf(aes(fill = factor(wert))) + 
  scale_fill_manual(values = c("black","white")) + 
  theme_void() +
  theme(legend.position = "none")

```

```{r, echo = TRUE}
mornans_i(sf_object = brett1,col = "wert")

```


```{r}

```





```{r}

mati <- (matrix(c(0,0,1,0,1,1,0,1,0,0),ncol = 2,byrow = TRUE))

pol1 <- st_polygon(list(mati))
pol2 <- st_polygon(list(mati+1))
pol3 <- st_polygon(list(cbind(mati[,1]+1,mati[,2])))
pol4 <- st_polygon(list(mati+0.5))


ggplot(st_sfc(pol1,pol4)) + geom_sf()

st_relate(pol1,pol3)

st_touches(pol1,pol4,sparse = FALSE)

schachbrett_relate <- st_relate(schachbrett,schachbrett,"FF2F11212")

schachbrett_relate[23]

schachbrett %>%
  rowid_to_column() %>%
  slice(c(23,13,22,24,33)) %>%
  ggplot() + geom_sf() + geom_sf_label(aes(label = rowid))

```

