---
title: "Untitled"
output: html_document
---
```{r}
knitr::opts_chunk$set(echo = FALSE)
library(sf)
library(tidyverse)
library(cowplot)
library(biscale)
```


```{r}
gemeinden_zweitwohnung <- st_read("23_RaumAn3/data_raw/zweitwohnung_gemeinden.gpkg")

ggplot() + 
  geom_sf(data = gemeinden_zweitwohnung, aes(fill = ja_in_percent), colour = NA) + 
  labs(fill = "Ja Anteil (%)", title = "Zweitwohnungsinitiative") +
  scale_fill_viridis_c() +
  theme_void()
```

```{r}
library(biscale)

data <- gemeinden_zweitwohnung %>%
  filter(!is.na(ja_in_percent), !is.na(beteiligung_in_percent)) %>%
  bi_class(x = ja_in_percent, y = beteiligung_in_percent, style = "quantile", dim = 3)

map <- ggplot() +
  geom_sf(data = data, mapping = aes(fill = bi_class), color = "white", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkBlue", dim = 3) +
  labs(
    title = "",
    caption = "Ja Anteil und Stimmbeteiligung (jeweils in %) auf der Gemeindeebene"
  ) +
  bi_theme()

legend <- bi_legend(pal = "DkBlue",
                    dim = 3,
                    xlab = "%-Ja Anteil ",
                    ylab = "%-Beteiligung ",
                    size = 8)
finalPlot <- ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +
  draw_plot(legend, 0.1, .65, 0.2, 0.2)

finalPlot
```
