```{r, include=F, purl = F}
# knitr::opts_knit$set(root.dir = "14_Statistik2") 
```


Aus @crawley2015 [168]: Script an Tools/Packages des Moduls Research Methods angepasst


Import dataset [growth.csv](14_Statistik2/data/growth.csv)

```{r, message = F}
weight <- read_csv("14_Statistik2/data/growth.csv")
```



```{r}

weight_smry <- weight %>% 
  group_by(diet, supplement) %>%
  summarise(
    mean = mean(gain)
  )


ggplot(weight_smry, aes(diet, mean, fill = diet)) +
  geom_bar(stat = "identity") +
  facet_grid(.~supplement) +
  scale_fill_grey(guide = F) 
```


```{r}
model <- aov(gain~diet*supplement,weight)
summary(model)
```


```{r}

weight %>%
  group_by(diet, supplement) %>%
  summarise(
    n = n()
  ) %>%
  spread(supplement, n)


weight_smry <- weight %>% 
  group_by(diet, supplement) %>%
  summarise(
    n = n(),
    mean = mean(gain),
    se = sqrt(1.72/n)

  )


ggplot(weight_smry, aes(diet, mean, fill = diet)) +
  geom_bar(stat = "identity") +
  facet_grid(.~supplement) +
  scale_fill_grey(guide = F)  +
  geom_errorbar(aes(ymin = mean-se, ymax = mean+se),width = 0.2) 


```


```{r}
summary.lm(model)
```


```{r}
model <- lm(gain~diet+supplement,weight)
summary(model )
```



```{r}
supp2 <- factor(weight$supplement)


weight <- weight %>%
  mutate(
    supplement2 = ifelse(supplement %in% c("agrimore","supersupp"),"best","worst")
  )


```


```{r}
model2 <- lm(gain~diet+supplement2,weight)
anova(model ,model2)
```


```{r}
summary(model2)
```
