## Übungen 1


###	Übung 1.1: Assoziationstest

Bitte führt einen Assoziationstest zweier kategorialer Variablen (mit je zwei Ausprägungen) mit Chi-Quadrat und Fishers exaktem Test durch. Ihr habt zwei Möglichkeiten: (1) Ihr erhebt dazu selbst die Daten (wozu ihr euch auch in Teams zusammenschliessen könnt). Dabei könnt ihr sowohl Befragungen/Datenerhebung unter Mitstudierenden durchführen (etwa Nutzung Mac/Windows vs. männlich/weiblich) oder Daten zu anderen Objekten erheben. (2) Ihr nehmt zwei kategoriale Variablen aus einem der Novanimal-Datensätze ([Feldexperiment]('13_Statistik/data/2017_ZHAW_aggregated_menu_sales_NOVANIMAL.csv') oder [Gästebefragung](https://zenodo.org/record/3554884/files/2019_ZHAW_vonRickenbach_cleaned_recorded_survey_dataset_NOVANIMAL_anonym.csv?download=1)). Bitte formuliert in beiden Fällen vor der Datenerhebung/Datenextraktion eine Hypothese, d.h. eine Erwartungshaltung ob und welche Assoziation vorliegt und wenn ja warum.


###	Übung 1.2: t-Test

Werden in den Basis- und Interventionswochen unterschiedlich viele Gerichte verkauft?

- Definiere die Null- ($H_0$) und die Alternativhypothese ($H_1$).
- Führe einen t-Test mit dem Datensatz novanimal.csv durch.
- Welche Form von t-Test musst Du anwenden: einseitig/zweiseitig resp. gepaart/ungepaart?
- Wie gut sind die Voraussetzungen für einen t-Test erfüllt (z.B. Normalverteilung der Residuen und Varianzhomogenität)?
- Stelle deine Ergebnisse angemessen dar, d.h. Text mit Abbildung und/oder Tabelle 

<br>
Das gilt für alle Übungen und wird von euch auch an der Prüfung verlangt. Abzugeben sind am Ende 
  
    a. lauffähiges R-Skript
    b. begründeter Lösungsweg (Kombination aus R-Code, R Output 
       und dessen Interpretation)
    c. ausformulierter Methoden- und Ergebnisteil (für eine wiss.Arbeit).

