
```{r, message=FALSE, echo=FALSE, results='hide', warning=FALSE}

library(readr)
library(dplyr)
library(gmodels)


nova <- read_delim("13_Statistik1/data/novanimal.csv", delim = ";")


```

```{r, message=FALSE, echo=FALSE, results='hide', warning=FALSE}

# Unterscheiden sich unsere Stichprobe signifikant von der gesamten Population (N = 2138)? 
pop_canteen <- group_by(nova, gender, member) %>% 
  summarise(tot = n()) %>% # fasse die Variablen Geschlecht und Hochschulzugehörigkeit zusammen
  ungroup() %>%
  mutate(canteen_member = c("Mitarbeiterinnen", "Studentinnen", "Mitarbeiter", "Studenten"))

# Definiere einen Vektor mit erwarteten Häufigkeiten, beachte dabei die Reihenfolge 
pop_zhaw_exp <- c(.15,.32,.16,.37) # erwartete Verteilung der Population (summe muss 1 ergeben)
  
#berechne den Chi-Quadrat-Test
chi_sq <- chisq.test(pop_canteen$tot, p = pop_zhaw_exp)
chi_sq$expected # schaue dir die erwarteten Häufigkeiten an.
chi_sq

#Führe einen exakten Fisher Test durch? (tibble, ist eine ähnliche Funktion wie data.frame)
fisher_t <- tibble(member = c("Mitarbeiterinnen", "Studentinnen", "Mitarbeiter", "Studenten"),
  population = pop_zhaw_exp * 2138, # absolute Zahlen der Population Mitarbeiterinnen, Studentinnen, Mitarbeiter, Studenten
  stichprobe = pop_canteen$tot)

# pop_zhaw_2 <- matrix(c(333, 678, 336, 791, 159, 290, 181, 466),4,2) # erstelle Matrix mit 4 Zeilen und 2 Spalten
# dimnames(pop_zhaw_2) <- list(c("Mitarbeiterinnen", "Studentinnen", "Mitarbeiter", "Studenten"), c("Population","Stichprobe"))

fisher.test(fisher_t[ ,2:3])

```

Der $\chi^2$-Test sagt uns, dass die NOVANIMAL-Stichprobe von der Population signifikant unterscheidet($\chi^2$(`r chi_sq$parameter`) = `r round(chi_sq$statistic[[1]], digits = 3)`, *p* = `r round(chi_qs$p.value, digits = 3)`).

