## Übung B (SozOek)


###	Aufgabe 1:

Unterscheidet sich die novanimal-Stichprobe von der gesamten Population bezüglich Geschlecht und Hochschulzugehörigkeit? 


* Es wird angenommen, dass 15 Prozent aller Mitarbeitenden mit CampusCard weiblich sind. 16 Prozent der Population (N = 2138) sind Mitarbeiter und 37 Prozent Studenten.
* Definiert die Null- ($H_0$) und Alternativhypothese ($H_1$)
* Führt einen $\chi^2$-Test und anschliessend einen exakten Fishers-Test mit dem Datensatz novanimal.csv durch
* Fasst die Ergebnisse in einem Satz zusammen


###	Aufgabe 2: t-Test

Werden in den Basis- und Interventionswochen unterschiedlich viele Gerichte verkauft?

* Definiert die Null- ($H_0$) und Alternativhypothese ($H_1$)
* Führt einen t-Test mit dem Datensatz novanimal.csv durch
* Welche Form von t-Test müssen Sie anwenden? einseitig/zweiseitig? gepaart/ungepaart?
* Überprüft die Voraussetzungen für einen t-Test (verwendet dafür das classic_theme())
* Fasst die Ergebnisse in einem Satz zusammen





