
## Übung

### Logistic Regression

Datensatz [isolation.csv](16_Statistik4/data/isolation.csv)

In this example, the response variable is called incidence; a value of 1 means that an island was occupied by a particular species of bird, and 0 means that the bird did not breed there. The explanatory variables are the area of the island (km2) and the isolation of the island (distance from the mainland, km).
<!-- Beispiel Crawley (pp. 275-276) -->
<!-- Die Studis brauchen den relativ komplizierten Code von S. 276 unten – 278, um die Güte des Fits zu visualisieren, nicht machen, da wir das im Kurs auch nicht besprechen. -->





### Split-plot ANOVA-Versuchsdesign

Datensatz [splityield.csv](16_Statistik4/data/splityield.csv)


In a split-plot experiment, different treatments are applied to plots of different sizes. Each different plot size is associated with its own error variance, so instead of having one error variance (as in all the ANOVA tables up to this point), we have as many error terms as there are different plot sizes. The analysis is presented as a series of component ANOVA tables, one for each plot size, in a hierarchy from the largest plot size with the lowest replication at the top, down to the smallest plot size with the greatest replication at the bottom. The example refers to a designed field experiment on crop yield with three treatments: irrigation (with two levels, irrigated and not), sowing density (with three levels, low, medium and high), and fertilizer application (with three levels, low, medium and high).

The largest plots were the four whole fields (block), each of which was split in half, and irrigation was allocated at random to one half of the field. Each irrigation plot was split into three, and one of three different seed-sowing densities (low, medium or high) was allocated at random (independently for each level of irrigation and each block). Finally, each density plot was divided into three and one of three fertilizer nutrient treatments (N, P, or N and P together) was allocated at random.
<!-- Beispiel Crawley (pp. 174-176) -->



