```{r, include=FALSE, purl=F}

knitr::opts_chunk$set(echo = TRUE,include = T, results = "hide",collapse=TRUE)
```
## Statistik 5 - Demoskript 

*_(c) Juergen Dengler, 05.11.2018_*

**Split-plot ANOVA**

_Based on Logan (2010), Chapter 14_

```{r}
spf<-read.csv("17_Statistik5/data/spf.csv")
spf.aov<-aov(Y~A*C+Error(B),spf)
summary(spf.aov)

attach(spf)
interaction.plot(C,A,Y)

#nun als LMM

library(nlme)
spf.lme.1<-lme(Y~A*C,random = ~C | B, spf)
spf.lme.2<-lme(Y~A*C,random = ~1 | B, spf)

anova(spf.lme.1)
anova(spf.lme.2)

summary(spf.lme.1)
summary(spf.lme.2)

## GLMM
#  Based on Zuur et al. (2009), chapter 13

DeerEcervi <- read.table("17_Statistik5/data/DeerEcervi.txt", header=TRUE, dec=".")

DeerEcervi$Ecervi.01 <- DeerEcervi$Ecervi

#Anzahl Larven hier in Presence/Absence uebersetzt
DeerEcervi$Ecervi.01[DeerEcervi$Ecervi>0]<-1
DeerEcervi$fSex <- factor(DeerEcervi$Sex)

#Hirschlänge hier standardisiert, sonst würde der Achsenabschnitt im Modell für
#einen Hirsch der Länge 0 modelliert, was schlecht interpretierbar ist, 
#jetzt ist der Achsenabschnitt für einen durschnittlich langen Hirsch
DeerEcervi$CLength <- DeerEcervi$Length - mean(DeerEcervi$Length)
DeerEcervi$fFarm <- factor(DeerEcervi$Farm)

#Zunächst als GLM
#Interaktionen mit fFarm nicht berücksichtigt, da zu viele Freiheitsgrade verbraucht würden
DE.glm<-glm(Ecervi.01 ~ CLength * fSex+fFarm, data = DeerEcervi,
            family = binomial)
drop1(DE.glm, test = "Chi")
summary(DE.glm)
anova(DE.glm)


plot(DeerEcervi$CLength,DeerEcervi$Ecervi.01,
     xlab="Length",ylab="Probability of \
     presence of E. cervi L1",main="Male data")

#der folgende Teil sollte die response curves für die einzelnen Farmen plotten
#aus irgendeinem Grund funktioniert er aber nicht
I<-order(DeerEcervi$CLength)
AllFarms<-unique(DeerEcervi$Farm)
for (j in AllFarms){
  mydata<-data.frame(CLength=DeerEcervi$CLength,fSex="1",
                     fFarm=AllFarms[j])
  n<-dim(mydata)[1]
  if (n>10){
    P.DE2<-predict(DE.glm,mydata,type="response")
    lines(mydata$CLength[I],P.DE2[I])
  }}

library(MASS)
DE.PQL<-glmmPQL(Ecervi.01 ~ CLength * fSex,
                random = ~ 1 | fFarm, family = binomial, data = DeerEcervi)
summary(DE.PQL)


#Aus online-Skript, nicht klar wozu das gemacht wird
eta <- fitted(DE.PQL)
fv  <- exp(eta)/(1+exp(eta))
res.raw <- DeerEcervi$Ecervi.01 - fv
res.P <- (DeerEcervi$Ecervi.01 - fv) / sqrt(fv * (1-fv))
sd(res.P)


intervals(DE.PQL,which="var-cov")


DE.PQL1<-glmmPQL(Ecervi.01 ~ CLength * fSex,
                 random = ~ 1 | fFarm,
                 family = quasi(link=logit,variance="mu(1-mu)"),
                 data = DeerEcervi)
summary(DE.PQL1)

g <- 0.8883697 + 0.0378608 * DeerEcervi$CLength
p.averageFarm1<-exp(g)/(1+exp(g))
I1<-order(DeerEcervi$CLength)              #Avoid spaghetti plot
plot(DeerEcervi$CLength,DeerEcervi$Ecervi.01,xlab="Length",
     ylab="Probability of presence of E. cervi L1")
lines(DeerEcervi$CLength[I1],p.averageFarm1[I],lwd=3)
p.Upp<-exp(g+1.96*1.462108)/(1+exp(g+1.96*1.462108))
p.Low<-exp(g-1.96*1.462108)/(1+exp(g-1.96*1.462108))
lines(DeerEcervi$CLength[I1],p.Upp[I1])
lines(DeerEcervi$CLength[I1],p.Low[I1])


library(lme4)
DE.lme4<-lmer(Ecervi.01 ~ CLength * fSex +(1|fFarm),
              family = binomial, data = DeerEcervi)
summary(DE.lme4)


library(glmmML)
DE.glmmML<-glmmML(Ecervi.01 ~ CLength * fSex,
                  cluster = fFarm,family=binomial, data = DeerEcervi)
summary(DE.glmmML)

g <- 0.8883697 + 0.0378608 * DeerEcervi$CLength
p.averageFarm1<-exp(g)/(1+exp(g))
I1<-order(DeerEcervi$CLength)              #Avoid spaghetti plot
plot(DeerEcervi$CLength,DeerEcervi$Ecervi.01,xlab="Length",
     ylab="Probability of presence of E. cervi L1")
lines(DeerEcervi$CLength[I1],p.averageFarm1[I],lwd=3)
p.Upp<-exp(g+1.96*1.462108)/(1+exp(g+1.96*1.462108))
p.Low<-exp(g-1.96*1.462108)/(1+exp(g-1.96*1.462108))
lines(DeerEcervi$CLength[I1],p.Upp[I1])
lines(DeerEcervi$CLength[I1],p.Low[I1])


library(lme4)
DE.lme4<-lmer(Ecervi.01 ~ CLength * fSex +(1|fFarm),
              family = binomial, data = DeerEcervi)
summary(DE.lme4)


library(glmmML)
DE.glmmML<-glmmML(Ecervi.01 ~ CLength * fSex,
                  cluster = fFarm,family=binomial, data = DeerEcervi)
summary(DE.glmmML)

```