```{r, include=F, purl = F}
# knitr::opts_knit$set(root.dir = "14_Statistik2")
```

<!-- @ Nils und Jürgen: würde DU Form verwenden -->
## Übung A (NatWis)

###	Aufgabe 1: Regression

Der Datensatz [decay.csv](14_Statistik2/data/decay.csv) beschreibt in einem physikalischen Experiment die Zahl der radioaktiven Zerfälle pro Minute in Abhängigkeit vom Zeitpunkt (min nach Start des Experimentes).
Laden Sie den Datensatz in R, machen Sie eine explorative Datenanalyse und wählen dann unter den schon gelernten Methoden der Regressionsanalyse ein adäquates Vorgehen zur Analyse dieser Daten, führen Sie diese durch, prüfen Sie anhand der Residuen, ob die Modellvoraussetzungen erfüllt waren, und stellen Sie die erhaltenen Ergebnisse angemessen dar (Text, Abbildung und/oder Tabelle). Kennen Sie ggf. noch eine andere geeignete Herangehensweise?



### Aufgabe 2: ANOVA
Der Datensatz [kormoran.csv](14_Statistik2/data/kormoran.csv) enthält 40 Beobachtungen zu Tauchzeiten zweier Kormoranunterarten (C = *Phalocrocorax carbo carbo* und S = *Phalacrocorax carbo sinensis*) aus vier Jahreszeiten (F = Frühling, S = Sommer, H = Herbst, W = Winter). Lesen Sie den Datensatz nach R ein und führen Sie eine adäquate Analyse durch, um beantworten zu können, wie Unterart und Jahreszeit die Tauchzeit beeinflussen. Stellen Sie Ihre Ergebnisse dann angemessen dar (Text, Abbildung und/oder Tabelle).

Datensatz anbei. Analyse geht wie Beispiel unter 1.5







