```{r, include=F, purl = F}
# knitr::opts_knit$set(root.dir = "14_Statistik2")
```

## Übung B (SozOek)


###	Aufgabe 1: einfaktorielle ANOVA

Führt mit dem Datensatz novanimal.csv eine einfaktorielle ANOVA durch. 
Gibt es Unterschiede zwischen der Anzahl verkaufter Gerichte (Buffet, Fleisch oder Vegetarisch) pro Woche? 

Hinweise für die Analysen: 

* Fasst die vier Inhalte der Gerichte zu drei Inhalten zusammen. Das heisst, dass die pflanzlichen Gerichte neu zu den vegetarischen Gerichten gezählt werden. Konkret könnt ihr das in R mit einer Umbenennung der Inhalte durchführen (z. B. mit grep()). 
* Danach muss der Datensatz gruppiert und zusammengefasst werden.
* Unbekannte Menü-Inhalte können vernachlässigt werden. 
* Wie gut sind die Voraussetzungen für eine ANOVA erfüllt? Wären allenfalls auch nicht-parametrische Analysen zulässig?
* Führt anschliessend Post-hoc-Vergleiche durch.
* Fasst die Ergebnisse in einem Satz zusammen.


###	Aufgabe 2: ANOVA mit Interaktion

Führt mit dem Datensatz novanimal.csv eine ANOVA mit Interaktion durch.

Können die Unterschiede in den verkauften Gerichten (Buffet, Fleisch oder Vegetarisch) durch die beiden Bedingungen (Basis- oder Interventionswochen) erklärt werden?

Hinweise für die Analysen: 

* Fasst die vier Inhalte der Gerichte zu drei Inhalten zusammen. Das heisst, dass die pflanzlichen Gerichte neu zu den vegetarischen Gerichten gezählt werden. Konkret könnt ihr das in R mit einer Umbenennung der Inhalte durchführen (z. B. mit grep()). 
* Danach muss der Datensatz gruppiert und zusammengefasst werden.
* Unbekannte Menü-Inhalte können vernachlässigt werden.
* Wie gut sind die Voraussetzungen für eine ANOVA erfüllt? Wären allenfalls auch nicht-parametrische Analysen zulässig?
* Führt anschliessend Post-hoc-Vergleiche durch.
* Fasst die Ergebnisse in einem Satz zusammen.