```{r, include=F, purl = F}
# knitr::opts_knit$set(root.dir = "14_Statistik2")
```



##	Übungen

### Aufgabe 1: Regression (deng)
Der Datensatz [decay.csv](14_Statistik2/data/decay.csv) beschreibt in einem physikalischen Experiment die Zahl der radioaktiven Zerfälle pro Minute in Abhängigkeit vom Zeitpunkt (min nach Start des Experimentes).
Laden Sie den Datensatz in R, machen Sie eine explorative Datenanalyse und wählen dann unter den schon gelernten Methoden der Regressionsanalyse ein adäquates Vorgehen zur Analyse dieser Daten, führen Sie diese durch, prüfen Sie anhand der Residuen, ob die Modellvoraussetzungen erfüllt waren, und stellen Sie die erhaltenen Ergebnisse angemessen dar (Text, Abbildung und/oder Tabelle). Kennen Sie ggf. noch eine andere geeignete Herangehensweise?



### Aufgabe 2: ANOVA (deng)
Der Datensatz [kormoran.csv](14_Statistik2/data/kormoran.csv) enthält 40 Beobachtungen zu Tauchzeiten zweier Kormoranunterarten (C = *Phalocrocorax carbo carbo* und S = *Phalacrocorax carbo sinensis*) aus vier Jahreszeiten (F = Frühling, S = Sommer, H = Herbst, W = Winter). Lesen Sie den Datensatz nach R ein und führen Sie eine adäquate Analyse durch, um beantworten zu können, wie Unterart und Jahreszeit die Tauchzeit beeinflussen. Stellen Sie Ihre Ergebnisse dann angemessen dar (Text, Abbildung und/oder Tabelle).

Datensatz anbei. Analyse geht wie Beispiel unter 1.5



### Aufgabe 3: ANOVA (egel)

Führt mit dem Datensatz novanimal.csv eine ANOVA durch (Aufbereitung der Daten, visuelle Inspektion der Modellvoraussetzung, Berechnung des Modells, Darstellung und Interpretation der Ergebnisse). 
Gibt es Unterschiede zwischen den verkauften Menü-Inahlten (Fleisch oder Fisch, Hot and Cold Buffet und Vegetarisch) pro Woche? Können die Unterschiede zwischen den Menü-Inhalten durch die Experimentalbedingungen erklärt werden?

Ihre Gesamtaufgabe ist es, aus den Daten ein zwei adäquates Modelle zu ermitteln. 

**Abzugeben sind am Ende (a) Ein lauffähiges R-Skript; (b) begründeter Lösungsweg (Kombination aus R-Code, R Output und dessen Interpretation) und (c) ausformulierter Methoden- und Ergebnisteil**

Hinweise für die Analysen: 
* Menü-Inhalt wird zu drei Gruppen zusammengefasst (pflanzliche Menüs = vegetarische Menüs)
* Der Datensatz muss zuerst Gruppiert werden (Wochen, Menü-Inhalt, Beschreibung der Experimentalwochen, Geschlecht, Hochschulzugehörigkeit)
* Posthoc Vergleiche mit dunnTest (FSA Package)

<!-- Zusätzliche Analysen: -->
<!-- - Alternativ kann das Alter in den Analysen berücksichtigt werden. Hierfür müssen Altersgruppen gebiltet werden. -->
<!-- - Hinweis: bildet Altersgruppen ... mittels der "cut" Funktion -->






