---
title: "MSc. Research Methods - Statistikteil Lösungen 2019"
author: "Juergen Dengler"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

## Musterlöseung Aufgabe 6.1: PCA


```{r,include=FALSE}
knitr::opts_chunk$set(fig.width = 20, fig.height = 12, warning = F, message = F, fig.pos = 'H',results = "hide")
```

```{r}
load("Doubs.RData")

summary(env)
summary(spe)

if(!require(vegan)){install.packages("vegan")}
library("vegan")

env.pca <- rda(env, scale=TRUE)
env.pca
summary(env.pca,axes=0)
summary(env.pca)
screeplot(env.pca, bstick=TRUE, npcs=length(env.pca$CA$eig))

par(mfrow=c(2,2))
biplot(env.pca, scaling=1)
biplot(env.pca, choices=c(1,3),scaling=1)
biplot(env.pca, choices=c(1,4),scaling=1)

scores<-scores(env.pca,choices=c(1:4),display=c("sites"))
scores

#Berechnung der Artenzahl mittels specnumber; Artenzahl und Scores werden zum Dataframe für die Regressionsanalyse hinzugefügt
doubs <- data.frame(env, scores, species_richness=specnumber(spe))
doubs
str(doubs)

##Lösung mit lm (alternativ ginge Poisson-glm) und frequentist approach (alternativ ginge Multimodelinference mit AICc)
lm.pc.0 <- lm(species_richness ~ PC1+PC2+PC3+PC4, data = doubs)
summary(lm.pc.0)

#Modellvereinfachung: PC4 ist nicht signifikant und wird entfernt
lm.pc.1 <- lm(species_richness ~ PC1+PC2+PC3, data = doubs)
summary(lm.pc.1) #jetzt sind alle Achsen signifikant und werden in das minimal adäquate Modell aufgenommen

#Modelldiagnostik/Modellvalidierung
par(mfrow=c(2,2))
plot(lm.pc.1) 

#Alternativ mit glm
glm.pc.0 <- glm(species_richness ~ PC1+PC2+PC3+PC4, family = "poisson", data = doubs)
summary(glm.pc.0)
glm.pc.1 <- glm(species_richness ~ PC1+PC2+PC3, family = "poisson", data = doubs)
summary(glm.pc.1)
plot(glm.pc.1) #sieht nicht besser aus als LM, die Normalverteilung ist sogar schlechter


###Zum Vergleich die Modellierung mit den Originaldaten

#Korrelationen zwischen Prädiktoren
cor <- cor(doubs[,1:11])
cor[abs(cor)<.7] <-0
cor #

#Globalmodell (als hinreichend unabhängige Variablen werden ele, slo, pH und pho aufgenommen)
lm.orig.0 <- lm(species_richness ~ ele+slo+pH+pho, data =doubs)
summary(lm.orig.0)

#Modellvereinfachung: slo als am wenigsten signifikante Variable gestrichen
lm.orig.1 <- lm(species_richness ~ ele+pH+pho, data =doubs)
summary(lm.orig.1)

#Modellvereinfachung: pH ist immer noch nicht signifikant und wird gestrichen
lm.orig.2 <- lm(species_richness ~ ele+pho, data =doubs)
summary(lm.orig.2)

#Modelldiagnostik
par(mfrow=c(2,2))
plot(lm.orig.2) #nicht so gut, besonders die Bananenform in der linken obereren Abbildung

#Versuch mit glm
glm.orig.0 <- glm(species_richness ~ ele+pho+pH+slo, family = "poisson", data =doubs)
summary(glm.orig.0)

glm.orig.1 <- glm(species_richness ~ ele+pho+slo, family = "poisson", data =doubs)
summary(glm.orig.1)

glm.orig.2 <- glm(species_richness ~ ele+pho, family = "poisson", data =doubs)
summary(glm.orig.2)
plot(glm.orig.2)

if(!require(AER)){install.packages("AER")}
library(AER)
dispersiontest(glm.orig.2) #signifikante Überdispersion

glmq.orig.2 <- glm(species_richness ~ ele+pho, family = "quasipoisson", data =doubs)
summary(glmq.orig.2)
plot(glmq.orig.2)
```
