```{r, include=FALSE, purl=F}

knitr::opts_chunk$set(echo = T, collapse=TRUE)
```

## Demo: Statistik Konsolidierung 1

*****

>Download [R-Skript](17_Statistik_Konsolidierung1/demoskript_assozationen.R)

*****

### Demo fuer Assoziationen------

```{r}

# state: november 2020
# author: gian-andrea egeler

#lade Packages
library(tidyverse)
library(magrittr)

#mytheme
mytheme <- 
  theme_classic() + 
  theme(
    axis.line = element_line(color = "black"), 
    axis.text = element_text(size = 20, color = "black"), 
    axis.title = element_text(size = 20, color = "black"), 
    axis.ticks = element_line(size = 1, color = "black"), 
    axis.ticks.length = unit(.5, "cm")
  )


```


```{r, message=FALSE}
#lade dateien
# mehr info darüber hier: https://cran.r-project.org/web/packages/explore/vignettes/explore_mtcars.html
mtcars %>% 
  as_tibble() %>% # da "nur" data frame kann glimplse nichts damit anfangen 
  glimpse()

# kline daten
df <- mtcars %>% as_tibble()

#assoziation zwischen anzahl zylinder und motorentyp ()
table(df$vs, df$am) # zur visualisierung: sieht aus, als gäbe es weniger v motoren bei den handgeschalteten

#lass und das überprüfen
#im wide format
chisq.test(df$am, df$vs)$expected

#fisher exacter test
fisher.test(df$am, df$vs)

```


```{r}

#t-test zwischen getriebe (v- vs. s-motor) und ps (pferdestärke)
# visualisierung
ggplot(df, aes(y = hp, x = factor(vs, levels = c("0", "1"),
                                  labels = c("Reihenmotor", "V-Motor")))) +
  stat_boxplot(geom ='errorbar', width = .25) +
  geom_boxplot() +
  labs(x = "\nBauform Motor", y = "Pferdestärke (PS)\n") +
  mytheme
       
boxplot(df$hp~df$vs) # sieht ganz ok aus

# t-test oder auch anova möglich
ttest <- t.test(df$hp ~ df$vs)
aov.1 <- aov(df$hp ~ df$vs)

#zeige resultate
ttest
summary.lm(aov.1)

```

 




