```{r, include=FALSE, purl=F}

knitr::opts_chunk$set(echo = T, collapse=TRUE)
```


# Konsolidierung Statistik 

In den vier Blöcken "Konsolidierung Statistik" repetieren die Studierenden wichtige Verfahren der Inferenz-Statistik. Beginnend mit den beiden einfachsten Fällen, dem Chi-Quadrat-Test für die Assoziation zwischen zwei kategorialen Variablen und dem t-Test auf Unterschiede in Mittelwerten zwischen zwei Gruppen, wiederholen die Studierende auch die Varianzanalyse (ANOVA) als Verallgemeinerung des t-Tests, einschliesslich post-hoc-Tests und mehrfaktorieller ANOVA. Weiter geht es mit der Repetition von komplexere Versionen linearer Regressionen und generalized linear models (GLMs), die einige wesentliche Limitierungen von linearen Modellen überwinden. Abschliessend bekommen die Studierenden eine Einführung in die Welt der Ordinationen z.B. PCA.


Für die nächsten drei gemeinsamen Sitzungen werden wir nochmals folgende Themen aufgreifen: 

Statistik Konsolidierung 1: Grundlagen der Statistik

*	Warum Statistik? Warum mit R?
*	Genereller Ablauf einer statistischen Analyse
*	Chi-Quadrat- bzw. Fishers Test (für kategoriale Daten)
*	t-Test (für metrische Daten)
*	Organisation der Übungen

Statistik Konsolidierung 2: Einführung in «multivariate» Methoden

*	Einführung in «multivariate» Methoden
*	Idee von Ordinationen
*	Hauptkomponentenanalyse (PCA)

Statistik Konsolidierung 3: Lineare Modelle I

*	Parametrische vs. nicht-parametrische Verfahren
*	Varianzanalyse (ANOVA vs. MANOVA vs. ANCOVA)
*	Lineare Modelle allgemein
*	Polynomische Regressionen
*	Multiple lineare Regressionen
*	Nicht-lineare Regressionen

Statistik Konsolidierung 4: Lineare Modelle II

*	Von linearen Modellen zu GLMs
*	Poisson-Regressionen für Zähldaten
*	Logistische Regressionen für Binärdaten
*	Glättungsfunktionen und GAMs
*	Gesamtüberblick und Wiederholung




