---
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Übung

Für die nächsten drei gemeinsamen Sitzungen (11./12./18. November) könnt ihr auf unterschiedlicher Weise die Methoden nochmals anwenden und üben.

    a. Ihr sucht euch einen eigenen Datensatz
    b. Ihr nehmt einen vorgeschlagenen Datensatz
    c. Ihr löst die alten Übungen noch einmal

**[Hier](different_datasets_190813_egel.html) habe ich eine kurze Übersicht zusammengestellt, wie ihr an Datensätzen gelangen könnt und [hier]() findet ihr eine Liste von vorgeschlagenen Datensätzen**

**Wichtig:** Beachtet, dass ihr einen Datensatz sucht, mit dem folgende Analyse möglich sind:

1. Assoziationstests
2. ANOVAS
3. linerare Modelle


Für eine gute Prüfungsvorbereitung erfasst ihr (Einzel oder als Gruppe) zu jeder obigen Analysemethode einen kurzen Bericht (max. 1/2 bis 1 Seite). Dieser Bericht beinhaltet folgende Punkte:

    a. lauffähiges R-Skript
    b. begründeter Lösungsweg (Kombination aus R-Code, R Output 
       und dessen Interpretation)
    c. ausformulierter Methoden- und Ergebnisteil (für eine wiss.Arbeit)
      * Methodenteil: Begründung wieso ihr euch für diese/n Test/Methode entschieden habt 
      * Ergebnisteil: Interpretation der Ergebnisse (ggf. mit Formel) und einer passenden Abbildung/Tabelle


Das Ziel dieser Übung ist es, 

- dass ihr euch überlegt was für eine Variablenstruktur der Datensatz aufweisen muss, um die obigen Analysen zu durchzuführen
- dass ihr einen eigenen Datensatz findet, welcher euer Interesse weckt
- dass ihr verschiedene Quellen zu Open Data gesehen und kennen gelernt habt 
- dass ihr für die Prüfung gut vorbereitet sind

*******
##### letztes Update `r Sys.Date()`, gian-andrea.egeler@zhaw.ch
