---
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gruppenarbeit

Für die nächsten drei gemeinsamen Sitzungen (11./12./18. November) werdet ihr einen eigenen Datensatz suchen und für eure Analysen aufbereiten. Nach jeder Sitzung werded ihr Zeit haben euch einer Methode zu widmen. Schliesst euch zu Gruppen zusammen - pro Gruppe nicht mehr als 4 Personen.

Ich habe euch [hier](different_datasets_190813_egel.html) eine kurze Übersicht zusammengestellt, wie ihr an Datensätzen gelangen könnt. 

**Wichtig:** Beachtet, dass ihr einen Datensatz sucht, mit dem folgende Analyse möglich sind:

1. Assoziationstests
2. ANOVAS
3. linerare Modelle


Das Ziel dieser Übung ist es, 

* dass ihr euch überlegt was für eine Variablenstruktur der Datensatz aufweisen muss, um die obigen Analysen zu druchzuführen
* dass ihr einen eigenen Datensatz findet, welcher euer Interesse weckt
* dass ihr verschiedene Quellen zu Open Data gesehen und kennen gelernt habt 
* dass ihr für die Prüfung gut vorbereitet sind


Für die Prüfungsvorbereitung erfasst ihr als Gruppe zu jeder obigen Analysemethode einen kurzen Bericht (max. 1/2 bis 1 Seite). Dieser Bericht beinhaltet folgende Punkte:

1. lauffähiges Skript mit Lösungsweg als Kommentare
2. ausformulierter Methoden- und Ergebnisteil
  * Methodenteil: Begründung wieso ihr euch für diese/n Test/Methode entschieden habt. 
  * Ergebnisteil: Interpretation der Ergebnisse (ggf. mit Formel) und einer passenden Grafik/Tabelle


*******
##### letztes Update `r Sys.Date()`, gian-andrea.egeler@zhaw.ch
