---
title: Demo Statistik 5
output: distill::distill_article
categories:
- Statistik5
---

```{r, include=FALSE, purl=F}
knitr::opts_chunk$set(echo = TRUE,include = T, results = "hide",collapse=TRUE)
```


**Von linearen Modellen zu GLMMs**
**(c) Juergen Dengler**


- [Demoscript als Download](17_Statistik5/RFiles/Statistik_5_Demo_v.05.R)
- Datensatz [spf.csv](https://github.com/ResearchMethods-ZHAW/datasets/raw/main/statistik/spf.csv)
- Datensatz [DeerEcervi.txt](https://github.com/ResearchMethods-ZHAW/datasets/raw/main/statistik/DeerEcervi.txt)


## Split-plot ANOVA
Based on Logan (2010), Chapter 14

```{r}
spf <- read.delim("spf.csv", sep = ";") 
spf.aov <- aov(Reaktion~Signal*Messung + Error(VP), data = spf)
summary(spf.aov)

interaction.plot(spf$Messung, spf$Signal, spf$Reaktion)

#nun als LMM
if(!require(nlme)){install.packages("nlme")}
library(nlme)
spf.lme.1 <- lme(Reaktion~Signal*Messung, random = ~Messung | VP, data = spf)
spf.lme.2 <- lme(Reaktion~Signal*Messung, random = ~1 | VP, data = spf)

anova(spf.lme.1)
anova(spf.lme.2)

summary(spf.lme.1)
summary(spf.lme.2)
```

## GLMM
Based on Zuur et al. (2009), chapter 13

```{r}
DeerEcervi <- read.delim("DeerEcervi.txt", sep = "")

DeerEcervi$Ecervi.01 <- DeerEcervi$Ecervi

#Anzahl Larven hier in Presence/Absence übersetzt
DeerEcervi$Ecervi.01[DeerEcervi$Ecervi>0] <- 1
DeerEcervi$fSex <- as.factor(DeerEcervi$Sex)

#Hirschlänge hier standardisiert, sonst würde der Achsenabschnitt im Modell für
#einen Hirsch der Länge 0 modelliert, was schlecht interpretierbar ist, 
#jetzt ist der Achsenabschnitt für einen durschnittlich langen Hirsch
DeerEcervi$CLength <- DeerEcervi$Length - mean(DeerEcervi$Length)
DeerEcervi$fFarm <- factor(DeerEcervi$Farm)


#Zunächst als GLM
#Interaktionen mit fFarm nicht berücksichtigt, da zu viele Freiheitsgrade verbraucht würden
DE.glm <- glm(Ecervi.01 ~ CLength * fSex+fFarm, family = binomial, data = DeerEcervi)

drop1(DE.glm, test = "Chi")
summary(DE.glm)
anova(DE.glm)
```

## GLMM

```{r}
if(!require(MASS)){install.packages("MASS")}
library(MASS)
DE.PQL <-glmmPQL(Ecervi.01 ~ CLength * fSex,
                random = ~ 1 | fFarm, family = binomial, data = DeerEcervi)
summary(DE.PQL)


g <- 0.8883697 + 0.0378608 * DeerEcervi$CLength
p.averageFarm1 <- exp(g)/(1+exp(g))
I <- order(DeerEcervi$CLength)              #Avoid spaghetti plot
plot(DeerEcervi$CLength, DeerEcervi$Ecervi.01, xlab="Length",
     ylab = "Probability of presence of E. cervi L1")
lines(DeerEcervi$CLength[I], p.averageFarm1[I],lwd=3)
p.Upp <- exp(g+1.96*1.462108)/(1+exp(g+1.96*1.462108))
p.Low <- exp(g-1.96*1.462108)/(1+exp(g-1.96*1.462108))
lines(DeerEcervi$CLength[I], p.Upp[I])
lines(DeerEcervi$CLength[I], p.Low[I])


if(!require(lme4)){install.packages("lme4")}
library(lme4)
DE.lme4 <- glmer(Ecervi.01 ~ CLength * fSex +(1|fFarm), family = binomial, data = DeerEcervi)
summary(DE.lme4)

if(!require(glmmML)){install.packages("glmmML")}
library(glmmML)
DE.glmmML <- glmmML(Ecervi.01 ~ CLength * fSex,
                  cluster = fFarm, family = binomial, data = DeerEcervi)
summary(DE.glmmML)
```
